# Generated by Django 2.1.4 on 2020-04-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=django.db.models.expressions.F('real_price'))),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
