# Generated by Django 2.2 on 2020-04-19 21:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=django.db.models.expressions.F('real_price'), null=True),
        ),
    ]
