# Generated by Django 2.2 on 2020-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20200419_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('egp', 'EGP')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
