# Generated by Django 2.2 on 2020-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_promo_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('egp', 'EGP')], default='percent', max_length=20),
        ),
    ]
