# Generated by Django 2.2 on 2020-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_auto_20200420_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('price', 'Price')], default='percent', max_length=20),
        ),
    ]
