# Generated by Django 2.2 on 2020-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_auto_20200420_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
