# Generated by Django 2.2 on 2020-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_auto_20200420_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_price',
            field=models.FloatField(),
        ),
    ]
