# Generated by Django 2.2 on 2020-04-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_auto_20200420_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='real_price',
        ),
        migrations.CreateModel(
            name='PlaceHolder',
            fields=[
                ('thething_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.TheThing')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('Payment.thething',),
        ),
    ]
