# Generated by Django 2.2 on 2020-04-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_auto_20200420_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Payment.PlaceHolder', unique=True),
            preserve_default=False,
        ),
    ]
