# Generated by Django 2.2 on 2020-04-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_order_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Promo'),
        ),
    ]
