# Generated by Django 2.2 on 2020-04-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0013_auto_20200420_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.TheThing', unique=True),
        ),
    ]
