# Generated by Django 2.2 on 2020-04-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0014_auto_20200420_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Payment.TheThing', unique=True),
        ),
    ]
