# Generated by Django 2.2 on 2020-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0015_auto_20200420_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
