# Generated by Django 2.2 on 2020-04-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0017_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Payment.TheThing'),
        ),
    ]
