# Generated by Django 2.2 on 2020-04-20 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0019_earn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Payment.TheThing'),
        ),
    ]
