# Generated by Django 2.2 on 2020-04-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0020_auto_20200420_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earn',
        ),
    ]
