# Generated by Django 2.2 on 2020-04-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePayment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
