# Generated by Django 2.2 on 2020-06-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranmodel', '0003_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
