# Generated by Django 2.2 on 2020-06-01 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='gg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seri.GG'),
        ),
    ]
