# Generated by Django 2.2 on 2020-06-30 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seri', '0002_auto_20200602_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gg',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1080)),
        ),
    ]
